import type { CueDefinition, CueId } from "@/soft-whisper/experience/types";

export const FINAL_MESSAGE =
  "That was your own voices, doing exactly what you were told, without a single utterance of \u201CWhy.\u201D Stay human.";

export const SWAN_LAKE_SEQUENCE = [
  "F#5", "B4", "C#5", "D5",
  "E5", "F#5", "D5", "F#5",
  "D5", "F#5", "B4", "D5",
  "B4", "G4", "D5", "B4",
  "E5", "D5", "C#5", "F#5",
  "B4", "C#5", "D5", "E5",
  "F#5", "D5", "F#5", "D5",
  "F#5", "B4", "D5", "B4",
  "G4", "D5", "B4",
] as const;

export const NOTE_RELEASE_SECONDS = [
  2.2, 1.55, 1.45, 1.55,
  1.95, 1.4, 1.35, 1.65,
  2.0, 1.5, 1.4, 1.55,
  1.95, 1.45, 1.45, 2.35,
  1.35, 1.25, 1.3, 2.15,
  1.55, 1.45, 1.55, 1.95,
  1.4, 1.35, 1.65, 2.0,
  1.5, 1.4, 1.55, 1.95,
  1.45, 1.45, 2.55,
] as const;

export const NOTE_INTERVAL_SECONDS = 0.74;

export const CLIMAX_CHANT_PHRASES = [
  "Are you ready for this experience?",
  "Again. Louder.",
  "Is everybody listening?",
  "Listen very carefully.",
  "Turn the handle.",
  "Look inside the box.",
];

export const cues: Record<CueId, CueDefinition> = {
  idle: {
    id: "idle",
    kicker: "",
    title: "",
    body: "",
    speech: "",
    minPromptMs: 500,
    gateKind: "none",
  },
  modeChoice: {
    id: "modeChoice",
    kicker: "",
    title: "Are you by yourself, or with a group of people?",
    body: "",
    speech: "Are you by yourself, or with a group of people?",
    minPromptMs: 600,
    gateKind: "none",
  },
  aloneLocked: {
    id: "aloneLocked",
    kicker: "",
    title: "This route is closed.",
    body: "The box only opens for a crowd.",
    speech: "This route is closed. The box only opens for a crowd.",
    minPromptMs: 2000,
    gateKind: "none",
  },
  crowdBoot: {
    id: "crowdBoot",
    kicker: "",
    title: "Hold still.",
    body: "The box is listening to the room.",
    instruction: "Microphone access is required.",
    speech: "Hold still. The box is listening to the room.",
    minPromptMs: 1800,
    gateKind: "none",
  },
  readyPrompt1: {
    id: "readyPrompt1",
    kicker: "",
    title: "Ask everyone: are you ready?",
    body: "Everyone, including you, should say yes.",
    speech: "Volunteer. Ask everyone. Are you ready for this experience?",
    retrySpeech: "Ask them again. Are you ready for this experience?",
    minPromptMs: 1500,
    gateKind: "affirmation",
  },
  readyPrompt2: {
    id: "readyPrompt2",
    kicker: "",
    title: "Louder.",
    body: "Ask again. Everyone must answer.",
    speech: "Again. Louder. Are you ready for this experience?",
    retrySpeech: "Louder. Ask them again.",
    minPromptMs: 1500,
    gateKind: "affirmation",
  },
  handlePhaseA: {
    id: "handlePhaseA",
    kicker: "",
    title: "Turn the handle.",
    body: "Press the up arrow two times for each turn. Let every note breathe before you wind again.",
    speech: "Turn the handle by pressing the up arrow.",
    minPromptMs: 900,
    gateKind: "none",
  },
  listeningPrompt1: {
    id: "listeningPrompt1",
    kicker: "",
    title: "Ask if everybody is listening.",
    body: "Everyone should answer.",
    speech: "Pause. Ask everyone. Is everybody listening?",
    retrySpeech: "Ask again. Is everybody listening?",
    minPromptMs: 1400,
    gateKind: "affirmation",
  },
  listeningPrompt2: {
    id: "listeningPrompt2",
    kicker: "",
    title: "Say it louder.",
    body: "Ask them again.",
    speech: "Louder. Is everybody listening?",
    retrySpeech: "Louder.",
    minPromptMs: 1400,
    gateKind: "affirmation",
  },
  handlePhaseB: {
    id: "handlePhaseB",
    kicker: "",
    title: "Keep turning.",
    body: "The notes are fading. Stay with the tempo and listen closely.",
    speech: "Continue turning the handle.",
    minPromptMs: 900,
    gateKind: "none",
  },
  carefulPrompt: {
    id: "carefulPrompt",
    kicker: "",
    title: "Tell them to listen very carefully.",
    body: "The melody is almost gone. Ask everyone to come closer.",
    speech: "Ask everyone to listen very carefully.",
    minPromptMs: 1800,
    gateKind: "none",
  },
  interiorReveal: {
    id: "interiorReveal",
    kicker: "",
    title: "Look inside the box.",
    body: "It is almost too faint to see.",
    speech: "Look inside the box.",
    minPromptMs: 2600,
    gateKind: "none",
  },
  ballerinaSilence: {
    id: "ballerinaSilence",
    kicker: "",
    title: "Stay quiet.",
    body: "Look carefully. Stay with her for a moment.",
    speech: "Stay quiet. Look carefully.",
    minPromptMs: 2200,
    gateKind: "none",
  },
  voiceBlast: {
    id: "voiceBlast",
    kicker: "",
    title: "",
    body: "",
    speech: "",
    minPromptMs: 1200,
    gateKind: "none",
  },
  messageHold: {
    id: "messageHold",
    kicker: "",
    title: "",
    body: FINAL_MESSAGE,
    speech: "",
    minPromptMs: 3000,
    gateKind: "none",
  },
  closeReset: {
    id: "closeReset",
    kicker: "",
    title: "",
    body: "",
    speech: "",
    minPromptMs: 2000,
    gateKind: "none",
  },
};
